apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-backend
  namespace: todo
  labels:
    app: todoapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp-backend
  template:
    metadata:
      name: todoapp-backend
      labels:
        app: todoapp-backend

    spec:
      containers:
        - name: todoapp
          image: pr8101999/todo_backend
          ports:
            - containerPort: 8000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todo-backend
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-backend
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todo-backend
                  key: DB_DATABASE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend
                  key: DB_HOST
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "8000"
