apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo
  labels:
    app: todoapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp-frontend
  template:
    metadata:
      name: todoapp-frontend
      labels:
        app: todoapp-frontend

    spec:
      containers:
        - name: ReactApp
          image: pr8101999/todo_frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_BASE_URL
              value: http://localhost:8000/api/v1
